module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.8-unstable
cabal-file: project.cabal
hidden-packages: ''
version: 1
extra-packages: ! 'Hackage: hslogger 1.2.3

  Hackage: exceptions 0.3.2

  Hackage: network-simple 0.3.0

'
ghc-args:
- -Wall
excluded-modules:
- Setup.hs
