binary-ghc-args:
- -O
- -threaded
module-template: ! "-----------------------------------------------------------------------------\n--
  |\n-- Module      :  MODULE_NAME\n-- Copyright   :  (c) Phil Hargett 2014\n-- License
  \    :  MIT (see LICENSE file)\n-- \n-- Maintainer  :  phil@haphazardhouse.net\n--
  Stability   :  experimental\n-- Portability :  non-portable (requires STM)\n--\n--
  (..... module description .....)\n--\n-----------------------------------------------------------------------------\n\nmodule
  MODULE_NAME (\n) where\n\n-- local imports\n\n-- external imports\n\n--------------------------------------------------------------------------------\n--------------------------------------------------------------------------------\n"
extensions: {}
environment: ghc-7.8-stable-14.09
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ''
ghc-args:
- -Wall
excluded-modules:
- Setup.hs
